#!/bin/zsh
if [[ $1 == "-h" ]]; then
  echo "kc - get list of contexts"
  echo "kc <ctxname> - set context"
elif [[ -n "$1" ]]; then
  kubectl config use-context $1
else
  kubectl config get-contexts
fi
