font:
  normal:
    family: Jetbrains Mono
    style: Variable
  size: 12.0

window:
  dynamic_padding: true

shell:
  program: /usr/bin/env
  args:
    - zsh
    - -l
    - -c
    - "tmux attach || tmux"

hints:
  enabled:
    - regex: '(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>"\s\{-\}\^`]+'
      hyperlinks: true
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: None

key_bindings:
  - { key: D,        mods: Command,              chars: "\x1bd"          }
  - { key: D,        mods: Command|Shift,        chars: "\x1bD"          }
  - { key: W,        mods: Command,              chars: "\x1bw"          }
  - { key: T,        mods: Command,              chars: "\x1bt"          }

  # Quality of Life - macOS
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # one word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # one word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End

  # Steal keybinds from the Swedish layout 
  - { key: Key1,      mods: Alt,          chars: "\xA9"                  }
  - { key: Key2,      mods: Alt,          chars: "\x40"                  }
  - { key: Key3,      mods: Alt,          chars: "\xA3"                  }
  - { key: Key4,      mods: Alt,          chars: "\x24"                  }
  - { key: Key5,      mods: Alt,          chars: "∞"                     }
  - { key: Key6,      mods: Alt,          chars: "\xA7"                  }
  - { key: Key7,      mods: Alt,          chars: "\x7C"                  }
  - { key: Key8,      mods: Alt,          chars: "\x5B"                  }
  - { key: Key9,      mods: Alt,          chars: "\x5D"                  }
  - { key: Key0,      mods: Alt,          chars: "≈"                     }
  - { key: Minus,     mods: Alt,          chars: "\xB1"                  }

## sv_SE PC Layout ('{', '}', '\' and '|' characters):
#  - { key: Key7,      mods: Alt,          chars: "\x7B"                  }
#  - { key: Key0,      mods: Alt,          chars: "\x7D"                  }
#  - { key: Minus,     mods: Alt,          chars: "\x5C"                  }
#  - { key: Grave,     mods: Alt,          chars: "\x7C"                  }
  
  - { key: Key1,      mods: Alt|Shift,    chars: "\xA1"                  }
  - { key: Key2,      mods: Alt|Shift,    chars: "”"                     }
  - { key: Key3,      mods: Alt|Shift,    chars: "\xA5"                  }
  - { key: Key4,      mods: Alt|Shift,    chars: "\x24"                  }
  - { key: Key5,      mods: Alt|Shift,    chars: "‰"                     }
  - { key: Key6,      mods: Alt|Shift,    chars: "\xB6"                  }
  - { key: Key7,      mods: Alt|Shift,    chars: "\x5C"                  }
  - { key: Key8,      mods: Alt|Shift,    chars: "\x7B"                  }
  - { key: Key9,      mods: Alt|Shift,    chars: "\x7D"                  }
  - { key: Key0,      mods: Alt|Shift,    chars: "≠"                     }
  - { key: Minus,     mods: Alt|Shift,    chars: "\xBF"                  }

# Replace the default bindings for these as the VirtualKeycodes don't match reality
  - { key: Slash,     mods: Command,      action: DecreaseFontSize       }
  - { key: Minus,     mods: Command,      action: IncreaseFontSize       }

# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0xeee8d5'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x0698bd'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
