[colors.bright]
black = "0x0698bd"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0xeee8d5"

[font]
size = 12.0

[font.normal]
family = "Jetbrains Mono"
style = "Regular"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = '(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>"\s\{-\}\^`]+'

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "©"
key = "1"
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "2"
mods = "Alt"

[[keyboard.bindings]]
chars = "£"
key = "3"
mods = "Alt"

[[keyboard.bindings]]
chars = "$"
key = "4"
mods = "Alt"

[[keyboard.bindings]]
chars = "^"
key = 39
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = "7"
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = "8"
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = "9"
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = "0"
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 27
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 50
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Minus"
mods = "Command"

[shell]
args = ["zsh", "-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/env"

[window]
dynamic_padding = true
option_as_alt = "Both"
