font:
  normal:
    family: Jetbrains Mono
    style: Variable
  size: 12.0

window:
  dynamic_padding: true

shell:
  program: /bin/zsh
  args: 
    - '--login'

hints:
  enabled:
    - regex: '(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>"\s\{-\}\^`]+'
      hyperlinks: true
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: None

key_bindings:
  - { key: D,        mods: Alt,     chars: "\x1bd"                       }
  - { key: D,        mods: Alt|Shift,     chars: "\x1bD"                       }

# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0xeee8d5'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
